# Railway 配置文件
# 這個文件是可選的，Railway 會自動檢測 Next.js 專案

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  NODE_ENV = "production"
